server:
  port: 8005
  max-http-header-size: 512000
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  application:
    name: spring-camel-cxf-client

service:
  api:
    base-path: /services/camel-client
    swagger-path: /v2/api-docs
  log:
    pretty-print: true
  person-api:
    url : https://localhost
    port: 8001
    baseUrl : /services/person
    findAllPerson: /findAll
    findByNationalCode : /findByNationalCode
    personApiNetFile : keystore/person_api.jks
    personApiNetFilePassword: saber@123

camel:
  springboot:
    route-controller-thread-pool-size: 20000
    producer-template-cache-size: 7000
    consumer-template-cache-size: 7000
    jmx-management-statistics-level: extended
  servlet:
    mapping:
      context-path: ${service.api.base-path}/*
  component:
    http:
      connections-per-route: 2000
      max-total-connections: 20000
      connect-timeout: 30000
      socket-timeout: 30000
      connection-request-timeout: 30000
      connection-time-to-live: 30000
      use-global-ssl-context-parameters: true
      x509-hostname-verifier: NoopHostnameVerifier

  dataformat:
    json-jackson:
      auto-discover-object-mapper: true


management:
  endpoints:
    web:
      base-path: /actuators/${spring.application.name}
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'